/* (in) simple int array as parameter */
int sumitems(int *first, int nitems);

/* simple structure */
typedef struct MyItem_t {
      int  id;
      char *name;
} MyItem;

/* (in/out) simple struct as parameter (updated by the function) */
void populateSampleItem(MyItem *item);

/* array of structure */
typedef struct MyItems_t {
      int  count;       // elements count
      MyItem *elements; // array of MyItem
} MyItems;

/* (in/out) array of structure as parameter (updated by the function) */
void populateItems(MyItems *items);

/* (out) array of structure (generated by the function) */
MyItems *buildItems();